#!/usr/bin/env python3
"""Generate PROGRESS.md and site/assets/curriculum.js from the design spec.

The spec is the single source of truth for the curriculum. Both artifacts
are derived from it so they cannot drift. Existing tick marks in
PROGRESS.md are preserved across regeneration.
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SPEC = ROOT / "docs/superpowers/specs/2026-09-20-networking-curriculum-design.md"
PROGRESS = ROOT / "PROGRESS.md"
CURRICULUM_JS = ROOT / "site/assets/curriculum.js"

SLUGS = {
    "0": "phase-0-map",
    "L1": "phase-l1-linux-foundations",
    "1": "phase-1-link-layer",
    "2": "phase-2-network-layer",
    "3": "phase-3-transport-layer",
    "4": "phase-4-names-and-trust",
    "5": "phase-5-application-layer",
    "L2": "phase-l2-linux-internals",
    "6": "phase-6-linux-networking",
    "7": "phase-7-container-kubernetes",
    "8": "phase-8-cloud-internet",
    "9": "phase-9-observability",
}

# "### Phase L1 - Linux Working Knowledge (5 modules, ~13h)"
PHASE_RE = re.compile(
    r"^### Phase (?P<id>L?\d+) [—-] (?P<title>.+?) "
    r"\((?P<count>\d+) modules?, ~(?P<hours>\d+)h\)\s*$"
)
# "- `L1-03` Processes, signals, and **file descriptors** - ..."
MODULE_RE = re.compile(r"^- `(?P<id>L?\d+-\d+)`\s+(?P<title>.+?)\s*$")


def strip_md(text: str) -> str:
    """Remove inline markdown emphasis and code markers from a title."""
    text = re.sub(r"\*\*(.+?)\*\*", r"\1", text)
    text = re.sub(r"\*(.+?)\*", r"\1", text)
    return text.replace("`", "")


def parse_spec() -> list[dict]:
    if not SPEC.exists():
        sys.exit(f"spec not found: {SPEC}")

    phases: list[dict] = []
    current: dict | None = None
    in_fence = False

    for line in SPEC.read_text(encoding="utf-8").splitlines():
        if line.lstrip().startswith("```"):
            in_fence = not in_fence
            continue
        if in_fence:
            continue

        if line.startswith("#"):
            # Any heading ends the previous phase section. Checked before
            # the module regex so stray bullets under a later section can
            # never be attributed to the last phase.
            current = None

        m = PHASE_RE.match(line)
        if m:
            pid = m.group("id")
            if pid not in SLUGS:
                sys.exit(f"unknown phase id {pid!r}; add it to SLUGS")
            current = {
                "id": pid,
                "slug": SLUGS[pid],
                "title": strip_md(m.group("title")),
                "hours": int(m.group("hours")),
                "declared": int(m.group("count")),
                "modules": [],
            }
            phases.append(current)
            continue

        m = MODULE_RE.match(line)
        if m and current is not None:
            current["modules"].append(
                {"id": m.group("id"), "title": strip_md(m.group("title"))}
            )

    if not phases:
        sys.exit("parsed zero phases; the spec format changed")

    for p in phases:
        actual = len(p["modules"])
        if actual != p["declared"]:
            sys.exit(
                f"Phase {p['id']}: heading declares {p['declared']} modules "
                f"but {actual} are listed"
            )
        del p["declared"]

    return phases


def read_done() -> set[str]:
    """Module ids already ticked, so regeneration never loses progress."""
    if not PROGRESS.exists():
        return set()
    return set(
        re.findall(r"^- \[x\] `([^`]+)`", PROGRESS.read_text(encoding="utf-8"), re.M)
    )


def render_progress(phases: list[dict], done: set[str]) -> str:
    total = sum(len(p["modules"]) for p in phases)
    hours = sum(p["hours"] for p in phases)
    complete = sum(1 for p in phases for mod in p["modules"] if mod["id"] in done)

    out = [
        "# Progress",
        "",
        "<!-- GENERATED by tools/gen-curriculum.py from the design spec.",
        "     Tick boxes by hand; they survive regeneration.",
        "     Do not edit anything else here - it will be overwritten. -->",
        "",
        f"**{complete} / {total} modules complete** · ~{hours} hours total · "
        "study order is top to bottom.",
        "",
        "Spec: [design spec]"
        "(docs/superpowers/specs/2026-09-20-networking-curriculum-design.md)",
        "",
    ]
    for p in phases:
        pdone = sum(1 for mod in p["modules"] if mod["id"] in done)
        out.append(
            f"## Phase {p['id']} — {p['title']} "
            f"({pdone}/{len(p['modules'])}, ~{p['hours']}h)"
        )
        out.append("")
        out.append(f"`docs/{p['slug']}/`")
        out.append("")
        for mod in p["modules"]:
            box = "x" if mod["id"] in done else " "
            out.append(f"- [{box}] `{mod['id']}` {mod['title']}")
        out.append("")
    return "\n".join(out)


def render_js(phases: list[dict]) -> str:
    payload = json.dumps(phases, indent=2, ensure_ascii=False)
    return (
        "// GENERATED by tools/gen-curriculum.py from the design spec.\n"
        "// Do not edit by hand. Inlined as a script because file:// blocks the Fetch API.\n"
        f"window.CURRICULUM = {payload};\n"
    )


def main() -> None:
    check = "--check" in sys.argv
    phases = parse_spec()
    done = read_done()

    want = {PROGRESS: render_progress(phases, done), CURRICULUM_JS: render_js(phases)}

    if check:
        for path, content in want.items():
            have = path.read_text(encoding="utf-8") if path.exists() else None
            if have != content:
                print(f"stale: {path.relative_to(ROOT)}")
                sys.exit(1)
        sys.exit(0)

    for path, content in want.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")

    total = sum(len(p["modules"]) for p in phases)
    print(f"{total} modules across {len(phases)} phases")


if __name__ == "__main__":
    main()
